const CATALOG=[
{id:1,title:'سایه‌های نئونی',type:'movie',year:2026,genre:'اکشن',rating:8.7,duration:'2h 08m',desc:'یک مأمور سابق در شهری آینده‌نگر برای نجات برادرش وارد شبکه‌ای از توطئه‌ها می‌شود.',art:'NEON',color:'linear-gradient(145deg,#66263b,#10131b)',video:''},
{id:2,title:'آخرین ایستگاه',type:'movie',year:2025,genre:'درام',rating:8.3,duration:'1h 54m',desc:'مسافری تنها در آخرین قطار شب با تصمیمی روبه‌رو می‌شود که مسیر زندگی‌اش را عوض می‌کند.',art:'LAST',color:'linear-gradient(145deg,#384c61,#11151d)',video:''},
{id:3,title:'خط قرمز',type:'movie',year:2026,genre:'هیجانی',rating:8.9,duration:'2h 16m',desc:'یک تحلیلگر امنیتی فقط چند ساعت فرصت دارد تا یک حمله بزرگ را متوقف کند.',art:'RED',color:'linear-gradient(145deg,#8c2634,#160d13)',video:''},
{id:4,title:'سیگنال صفر',type:'movie',year:2024,genre:'علمی‌تخیلی',rating:8.1,duration:'1h 47m',desc:'سیگنالی ناشناس از اعماق فضا پاسخ‌هایی به همراه دارد که نباید شنیده می‌شدند.',art:'ZERO',color:'linear-gradient(145deg,#253e61,#0c111a)',video:''},
{id:5,title:'شهر خاموش',type:'movie',year:2025,genre:'معمایی',rating:8.5,duration:'2h 02m',desc:'پس از ناپدید شدن تمام ساکنان یک شهر، یک خبرنگار وارد منطقه ممنوعه می‌شود.',art:'SILENT',color:'linear-gradient(145deg,#4b465b,#111217)',video:''},
{id:6,title:'پشت دیوار',type:'series',year:2026,genre:'جنایی',rating:9.1,duration:'2 فصل',desc:'کارآگاهی که به هیچ‌کس اعتماد ندارد، پرونده‌ای را دنبال می‌کند که به گذشته خودش وصل است.',art:'WALL',color:'linear-gradient(145deg,#4a392e,#12100e)',episodes:[['1','قسمت ۱ — ورود',''],['2','قسمت ۲ — سرنخ',''],['3','قسمت ۳ — دروغ','']]},
{id:7,title:'مدار تاریک',type:'series',year:2025,genre:'علمی‌تخیلی',rating:8.8,duration:'1 فصل',desc:'گروهی از فضانوردان پس از قطع ارتباط زمین، با انتخابی غیرممکن روبه‌رو می‌شوند.',art:'ORBIT',color:'linear-gradient(145deg,#263d68,#0b101a)',episodes:[['1','قسمت ۱ — سکوت',''],['2','قسمت ۲ — مدار',''],['3','قسمت ۳ — بازگشت','']]},
{id:8,title:'پرونده 17',type:'series',year:2024,genre:'معمایی',rating:8.6,duration:'3 فصل',desc:'هر سرنخ یک راز قدیمی‌تر را آشکار می‌کند و پرونده‌ای که بسته شده بود دوباره باز می‌شود.',art:'17',color:'linear-gradient(145deg,#4e405e,#121018)',episodes:[['1','قسمت ۱ — پرونده',''],['2','قسمت ۲ — شاهد',''],['3','قسمت ۳ — اعتراف','']]},
{id:9,title:'خط ساحلی',type:'series',year:2026,genre:'درام',rating:8.0,duration:'1 فصل',desc:'چهار دوست بعد از سال‌ها به شهر ساحلی کودکی‌شان برمی‌گردند.',art:'COAST',color:'linear-gradient(145deg,#315c67,#10171a)',episodes:[['1','قسمت ۱ — بازگشت',''],['2','قسمت ۲ — خانه قدیمی','']]},
{id:10,title:'عملیات شب',type:'series',year:2025,genre:'اکشن',rating:8.4,duration:'2 فصل',desc:'یک تیم کوچک در عملیات‌هایی که نباید وجود داشته باشند، حقیقت را دنبال می‌کند.',art:'NIGHT',color:'linear-gradient(145deg,#40334d,#0e0d13)',episodes:[['1','قسمت ۱ — آماده‌سازی',''],['2','قسمت ۲ — نفوذ',''],['3','قسمت ۳ — خروج','']]}
];
let myList=JSON.parse(localStorage.getItem('cinewave_list')||'[]');let currentFilter='همه';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function card(x){const saved=myList.includes(x.id);return `<article class="card" data-id="${x.id}"><div class="poster"><div class="poster-art" style="background:${x.color}"><span>${esc(x.art)}</span></div><b class="badge">${x.type==='series'?'SERIES':'FILM'}</b></div><h3>${esc(x.title)}</h3><small>★ ${x.rating} · ${x.year} · ${esc(x.genre)}</small></article>`}
function renderGrid(id,list){$(id).innerHTML=list.length?list.map(card).join(''):'<div class="empty">هنوز موردی در این بخش وجود ندارد.</div>';$(id).querySelectorAll('.card').forEach(e=>e.onclick=()=>openDetails(+e.dataset.id))}
function render(){const movies=CATALOG.filter(x=>x.type==='movie'&&(currentFilter==='همه'||x.genre===currentFilter));renderGrid('#popularGrid',CATALOG.slice(0,6));renderGrid('#movieGrid',movies);renderGrid('#seriesGrid',CATALOG.filter(x=>x.type==='series'));renderGrid('#myListGrid',CATALOG.filter(x=>myList.includes(x.id)));$('#listCount').textContent=`${myList.length} عنوان`;$('#movieChips').innerHTML=['همه',...new Set(CATALOG.filter(x=>x.type==='movie').map(x=>x.genre))].map(g=>`<button class="chip ${g===currentFilter?'active':''}" data-g="${esc(g)}">${esc(g)}</button>`).join('');$('#movieChips').querySelectorAll('.chip').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.g;render()})}
function openDetails(id){const x=CATALOG.find(a=>a.id===id);if(!x)return;const saved=myList.includes(id);$('#detailsContent').innerHTML=`<div class="detail-top" style="background:linear-gradient(90deg,#0e1219 0%,rgba(14,18,25,.7) 55%,rgba(14,18,25,.2)),${x.color}"><div class="eyebrow">${x.type==='series'?'SERIES':'MOVIE'}</div><h2>${esc(x.title)}</h2><div class="meta"><span>★ ${x.rating}</span><span>${x.year}</span><span>${esc(x.genre)}</span><span>${esc(x.duration)}</span></div><p>${esc(x.desc)}</p><div class="actions"><button class="btn primary" id="playBtn">▶ پخش</button><button class="btn secondary" id="listBtn">${saved?'✓ حذف از لیست':'＋ افزودن به لیست'}</button></div></div>${x.type==='series'?`<div class="detail-body"><h3>قسمت‌ها</h3>${x.episodes.map(e=>`<div class="episode"><span>${esc(e[1])}</span><button data-ep="${esc(e[0])}">▶ پخش</button></div>`).join('')}</div>`:''}`;$('#detailsModal').hidden=false;$('#playBtn').onclick=()=>play(x);$('#listBtn').onclick=()=>toggleList(id);$('#detailsContent').querySelectorAll('[data-ep]').forEach(b=>b.onclick=()=>play(x,b.dataset.ep))}
function play(x,ep=''){const src=x.type==='movie'?x.video:(x.episodes.find(e=>e[0]===ep)||[])[2];$('#playerTitle').textContent=ep?`${x.title} — قسمت ${ep}`:x.title;const v=$('#video');v.pause();v.removeAttribute('src');if(src){v.src=src;v.load();v.play().catch(()=>{})}else{v.load()}$('#playerModal').hidden=false}
function toggleList(id){myList=myList.includes(id)?myList.filter(x=>x!==id):[...myList,id];localStorage.setItem('cinewave_list',JSON.stringify(myList));openDetails(id);render();toast(myList.includes(id)?'به لیست من اضافه شد':'از لیست من حذف شد')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function hero(){const x=CATALOG[2];$('#hero').innerHTML=`<div class="hero-copy"><div class="eyebrow">پیشنهاد ویژه</div><h1>${esc(x.title)}</h1><div class="meta"><span>★ ${x.rating}</span><span>${x.year}</span><span>${esc(x.genre)}</span><span>${x.duration}</span></div><p>${esc(x.desc)}</p><div class="actions"><button class="btn primary" onclick="openDetails(${x.id})">▶ مشاهده</button><button class="btn secondary" onclick="toggleList(${x.id})">＋ لیست من</button></div></div>`}
$('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){render();return}const found=CATALOG.filter(x=>`${x.title} ${x.genre} ${x.type}`.toLowerCase().includes(q));renderGrid('#popularGrid',found);$('#popularGrid').closest('.section').querySelector('h2').textContent='نتایج جست‌وجو';window.scrollTo({top:document.querySelector('#home').offsetTop-70,behavior:'smooth'})});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').hidden=true);document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal').forEach(m=>m.hidden=true)});hero();render();
